title: My blog
description: 
author: "Nipun Ramani"

theme: minima

base_url: /blog

# Minima social links
twitter_username: ramaninipun
github_username:  BhayanakMoth
linkedin_username: nipun-ramani-0a8a07143


# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
